SELECT
HISTORY_VISITS.ID AS "HISTORY ITEM ID",
DATETIME(HISTORY_VISITS.VISIT_TIME+978307200,'UNIXEPOCH','UTC') AS "VISIT TIME",
HISTORY_ITEMS.URL,
HISTORY_ITEMS.VISIT_COUNT,
HISTORY_ITEMS.DAILY_VISIT_COUNTS,
HISTORY_ITEMS.WEEKLY_VISIT_COUNTS,
HISTORY_VISITS.TITLE,
HISTORY_VISITS.ORIGIN,
HISTORY_VISITS.LOAD_SUCCESSFUL,
HISTORY_VISITS.REDIRECT_SOURCE,
HISTORY_VISITS.REDIRECT_DESTINATION
FROM HISTORY_ITEMS
LEFT OUTER JOIN HISTORY_VISITS ON HISTORY_ITEMS.ID == HISTORY_VISITS.HISTORY_ITEM
ORDER BY "VISIT TIME"
