SELECT
ZABCDRECORD.ZUNIQUEID,
DATETIME(ZCREATIONDATE+978307200,'UNIXEPOCH','LOCALTIME') AS "CREATED",
DATETIME(ZMODIFICATIONDATE+978307200,'UNIXEPOCH','LOCALTIME') AS "MODIFIED",
ZFIRSTNAME,
ZLASTNAME,
ZABCDEMAILADDRESS.ZADDRESS,
ZABCDPHONENUMBER.ZFULLNUMBER
FROM ZABCDRECORD
LEFT JOIN ZABCDEMAILADDRESS ON ZABCDRECORD.Z_PK = ZABCDEMAILADDRESS.ZOWNER
LEFT JOIN ZABCDPHONENUMBER ON ZABCDRECORD.Z_PK = ZABCDPHONENUMBER.ZOWNER
