SELECT MESSAGES.ROWID, READ, FLAGGED, DELETED, DATETIME(DATE_SENT,'UNIXEPOCH','LOCALTIME') AS DATE_SENT, DATETIME(DATE_RECEIVED,'UNIXEPOCH','LOCALTIME') AS DATE_RECEIVED, DATETIME(DATE_CREATED,'UNIXEPOCH','LOCALTIME') AS DATE_CREATED, DATETIME(DATE_LAST_VIEWED,'UNIXEPOCH','LOCALTIME') AS DATE_LAST_VIEWED, MAILBOXES.URL, ADDRESSES.ADDRESS, SUBJECTS.SUBJECT, SNIPPET FROM MESSAGES
LEFT JOIN ADDRESSES ON MESSAGES.SENDER == ADDRESSES.ROWID
LEFT JOIN SUBJECTS ON MESSAGES.SUBJECT == SUBJECTS.ROWID
LEFT JOIN MAILBOXES ON MESSAGES.MAILBOX == MAILBOXES.ROWID
