SELECT
BUNDLE_ID,
DATETIME(INSTALL_DATE+978307200,'UNIXEPOCH','LOCALTIME') AS INSTALL_DATE, DATETIME(TIMESTAMP,'UNIXEPOCH','LOCALTIME') AS FIRST_INSTALL_DATE,
STORE_ITEM_DATA
FROM SOFTWARE_UPDATE
ORDER BY INSTALL_DATE DESC 
