SELECT
DATETIME(LAST_VIEWED_TIME+978307200,'UNIXEPOCH','LOCALTIME') AS “LAST_VIEWED_TIME",
ID,
UUID,
TITLE,
URL,
USER_VISIBLE_URL,
ORDER_INDEX,
PRIVATE_BROWSING,
OPENED_FROM_LINK,
SESSION_DATA
FROM TABS ORDER BY LAST_VIEWED_TIME
