SELECT
ZNOTE.Z_PK,
DATETIME(ZNOTE.ZCREATIONDATE+978307200,'UNIXEPOCH','LOCALTIME') AS CREATION DATE,
DATETIME(ZNOTE.ZMODIFICATIONDATE+978307200,'UNIXEPOCH','LOCALTIME') AS MODIFICATION DATE,
ZNOTE.ZDELETEDFLAG,
ZNOTE.ZSUMMARY,
ZNOTE.ZTITLE,
ZNOTE.ZAUTHOR,
ZNOTE.ZGUID,
ZACCOUNT.ZNAME AS ACCOUNT NAME,
ZNOTEBODY.ZCONTENT,
ZNOTEATTACHMENT.ZCONTENTID,
ZNOTEATTACHMENT.ZFILENAME
FROM ZNOTE
LEFT JOIN ZSTORE ON ZNOTE.ZSTORE == ZSTORE.Z_PK
LEFT JOIN ZACCOUNT ON ZSTORE.ZACCOUNT == ZACCOUNT.Z_PK
LEFT JOIN ZNOTEBODY ON ZNOTE.ZBODY == ZNOTEBODY.Z_PK
LEFT JOIN ZNOTEATTACHMENT ON ZNOTE.Z_PK == ZNOTEATTACHMENT.ZNOTE
ORDER BY CREATION DATE
