SELECT
ZICCLOUDSYNCINGOBJECT.Z_PK,
ZICCLOUDSYNCINGOBJECT.ZIDENTIFIER,
Z_12NOTES.Z_12FOLDERS AS 'NOTE FOLDER',
DATETIME(ZICCLOUDSYNCINGOBJECT.ZCREATIONDATE+978307200,'UNIXEPOCH','LOCALTIME') AS 'CREATE TIME',
DATETIME(ZICCLOUDSYNCINGOBJECT.ZMODIFICATIONDATE1+978307200,'UNIXEPOCH','LOCALTIME') AS 'MODIFICATION TIME',
DATETIME(ZICCLOUDSYNCINGOBJECT.ZFOLDERSMODIFICATIONDATE+978307200,'UNIXEPOCH','LOCALTIME') AS 'FOLDER MODIFICATION TIME',
ZICCLOUDSYNCINGOBJECT.ZTITLE1 AS 'NOTE TITLE',
ZICCLOUDSYNCINGOBJECT.ZSNIPPET,
ZICCLOUDSYNCINGOBJECT.ZISPASSWORDPROTECTED AS PROTECTED,
ZICCLOUDSYNCINGOBJECT.ZPASSWORDHINT,
ZICCLOUDSYNCINGOBJECT.ZMARKEDFORDELETION AS DELETED,
ZICNOTEDATA.ZDATA FROM ZICCLOUDSYNCINGOBJECT
LEFT JOIN ZICNOTEDATA ON ZICCLOUDSYNCINGOBJECT.ZNOTEDATA == ZICNOTEDATA.Z_PK
LEFT JOIN Z_12NOTES ON ZICCLOUDSYNCINGOBJECT.Z_PK == Z_12NOTES.Z_9NOTES
WHERE ZICCLOUDSYNCINGOBJECT.Z_ENT == 9 AND 'NOTE FOLDER' == 104
ORDER BY 'CREATE TIME'
