SELECT
DATETIME(PASS.INGESTED_DATE+978307200,'UNIXEPOCH','LOCALTIME') AS INGESTED DATE,
DATETIME(PASS.MODIFIED_DATE+978307200,'UNIXEPOCH','LOCALTIME') AS MODIFIED DATE,
PASS.UNIQUE_ID,
PASS.ORGANIZATION_NAME,
PASS_TYPE.IDENTIFIER,
PAYMENT_TRANSACTION.AMOUNT,
PAYMENT_TRANSACTION.CURRENCY_CODE,
PAYMENT_TRANSACTION.MERCHANT_INDUSTRY_CATEGORY,
PAYMENT_TRANSACTION.MERCHANT_NAME,
DATETIME(PAYMENT_TRANSACTION.TRANSACTION_DATE+978307200,'UNIXEPOCH','LOCALTIME') AS TRANSACTION DATE,
LOCATION.LATITUDE,
LOCATION.LONGITUDE,
LOCATION.RELEVANT_TEXT,
DATETIME(PASS.RELEVANT_DATE+978307200,'UNIXEPOCH','LOCALTIME') AS RELEVANT TIME,
DATETIME(PASS.PUSH_REGISTRATION_DATE+978307200,'UNIXEPOCH','LOCALTIME') AS PUSH REG TIME,
PASS.LAST_MODIFIED_TAG
FROM PASS
LEFT JOIN PASS_TYPE ON PASS.PASS_TYPE_PID == PASS_TYPE.PID
LEFT JOIN PAYMENT_TRANSACTION ON PASS.PID == PAYMENT_TRANSACTION.PASS_PID
LEFT JOIN LOCATION_SOURCE ON LOCATION_SOURCE.URL LIKE '%'||PASS.UNIQUE_ID||'%’
LEFT JOIN LOCATION ON LOCATION.LOCATION_SOURCE_PID == LOCATION_SOURCE.PID
