select
datetime(ZSLKBASECHANNEL.ZCREATED, 'unixepoch', 'localtime') as CreatedTime,
datetime(ZSLKBASECHANNEL.ZPURPOSELASTSET, 'unixepoch', 'localtime') as PurposeLastSet,
datetime(ZSLKBASECHANNEL.ZTOPICLASTSET, 'unixepoch', 'localtime') as TopicLastSet,
datetime(ZSLKBASECHANNEL.ZLASTREAD, 'unixepoch', 'localtime') as LastRead,
datetime(ZSLKBASECHANNEL.ZLATEST, 'unixepoch', 'localtime') as Latest,
ZSLKBASECHANNEL.ZNAME as ChannelNames,
ZSLKBASECHANNEL.ZTSID as DMChannels,
ZSLKBASECHANNEL.ZTSID1 as OtherChannels,
ZSLKBASECHANNEL.ZUSERID,
ZSLKBASECHANNEL.ZCREATORID,
ZSLKBASECHANNEL.ZPURPOSECREATORID,
ZSLKBASECHANNEL.ZPURPOSETEXT,
ZSLKBASECHANNEL.ZTOPICCREATORID,
ZSLKBASECHANNEL.ZTOPICTEXT,
ZSLKBASECHANNEL.ZSHAREDTEAMIDS
from ZSLKBASECHANNEL
