select distinct 
ZSLKMESSAGE.ZUSERID as MessageGeneratedFrom,
ZSLKCOREDATAUSER.ZREALNAME as MessageGeneratedFromName,
ZSLKCOREDATAUSER.ZNAME as MessageGeneratedFromNameAlt,
ZSLKBASECHANNEL.ZNAME as MessageSentToChannelName,
ZSLKMESSAGE.ZTEXT,
datetime(ZSLKMESSAGE.ZTIMESTAMP, 'unixepoch', 'localtime') as MessageTimeStamp,  
ZSLKMESSAGE.ZFILEIDS,
       json_extract(ZFILEIDS, '$[0]') as HasSharedFile,
ZSLKMESSAGE.ZCHANNELID,
ZSLKBASECHANNEL.ZTSID,
ZSLKBASECHANNEL.ZTSID1,
ZSLKCOREDATAUSER.ZTSID
from ZSLKMESSAGE, ZSLKBASECHANNEL,ZSLKCOREDATAUSER
where  ZSLKCOREDATAUSER.ZTSID = ZSLKMESSAGE.ZUSERID and 
(ZSLKBASECHANNEL.ZTSID = ZSLKMESSAGE.ZCHANNELID or ZSLKBASECHANNEL.ZTSID1 = ZSLKMESSAGE.ZCHANNELID)
order by ZSLKMESSAGE.ZTIMESTAMP
