select 
ZSLKCOREDATAUSER.ZADMIN,
ZSLKCOREDATAUSER.ZOWNER,
ZSLKCOREDATAUSER.ZREALNAME,
ZSLKCOREDATAUSER.ZFIRSTNAME,
ZSLKCOREDATAUSER.ZLASTNAME,
ZSLKCOREDATAUSER.ZDISPLAYNAME,
ZSLKCOREDATAUSER.ZNAME,
ZSLKCOREDATAUSER.ZPHONE,
ZSLKCOREDATAUSER.ZTIMEZONE,
ZSLKCOREDATAUSER.ZTIMEZONEOFFSET,
ZSLKCOREDATAUSER.ZTIMEZONETITLE,
ZSLKCOREDATAUSER.ZTITLE,
ZSLKCOREDATAUSER.ZTSID,
ZSLKCOREDATAUSER.ZTEAMID
from ZSLKCOREDATAUSER
